# Generated by Django 3.2.9 on 2021-12-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongaapp', '0002_auto_20211204_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='bonga/'),
        ),
    ]
