# Generated by Django 3.2.9 on 2021-12-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongaapp', '0009_alter_like_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('author', 'image'), name='unique_like'),
        ),
    ]
